### ISSUE TITLE
Error:Could not get unknown property 'MAVEN_REPOSITORY_URL'

### ISSUE THREAD

**Issue by amanjain08** [bubenheimer/androidrulez#1]

**Comment by bubenheimer** [comment]
The project is set up to work with my specific build environment. You'd either need to set this gradle property to point at a local Maven repository, or modify the build.gradle file to point directly at the needed repositories. (probably `google()` and `jcenter()`, in addition to pulling in some of the other needed dependencies from my Github).

This is a pretty low-key project at this point, so I won't be able to support it much beyond my own needs for now. I am actively using it myself, so as long as you can get it to build it should work for you. I am not versioning it for now, though, so APIs may break in the future without warning.

**Comment by bubenheimer** [comment]
Closing as obsolete. Project uses maven-publish these days and should be easier to build, but still requires building a few other dependencies from my Github.
